<#
  scripts/Generate-ProjectStructure.ps1
  Usage:
    .\Generate-ProjectStructure.ps1 -DevName "YourName" -CreateSampleFiles
  Notes:
    Repo name: NZFTC
    This creates a developer-root folder named NZFTC.<DevName> containing the project scaffold and starter files.
#>

param(
  [Parameter(Mandatory=$true)][string]$DevName,
  [string]$RepoName = "NZFTC",
  [switch]$CreateSampleFiles
)

# Developer root
$root = Join-Path (Get-Location) "$RepoName.$DevName"
if (-not (Test-Path $root)) {
  New-Item -ItemType Directory -Path $root -Force | Out-Null
  Write-Host "Created developer root: $root"
} else {
  Write-Host "Developer root exists: $root"
}

# Folder layout
$folders = @(
  "$root/src/$RepoName.Server",
  "$root/src/$RepoName.Data",
  "$root/src/$RepoName.UI",
  "$root/src/$RepoName.Shared",
  "$root/src/$RepoName.MockServices",
  "$root/tests/$RepoName.Tests.Unit",
  "$root/tests/$RepoName.Tests.Integration",
  "$root/docs",
  "$root/scripts",
  "$root/data",
  "$root/src/Contributions"
)

foreach ($f in $folders) {
  if (-not (Test-Path $f)) { New-Item -ItemType Directory -Path $f -Force | Out-Null; Write-Host "Created: $f" } else { Write-Host "Exists: $f" }
}

# solution placeholder
$solutionFile = Join-Path $root "$RepoName.sln"
if (-not (Test-Path $solutionFile)) { New-Item -ItemType File -Path $solutionFile -Force | Out-Null; Write-Host "Created solution placeholder: $solutionFile" }

if ($CreateSampleFiles) {
  # README
  $readme = Join-Path $root "README.md"
  @"
# $RepoName - Developer: $DevName

This scaffold was generated by scripts/Generate-ProjectStructure.ps1.
Developer root: $DevName
Repository: https://github.com/DeusEx-Projects-Group/$RepoName
"@ | Out-File -FilePath $readme -Encoding UTF8
  Write-Host "Created: $readme"

  # .editorconfig
  $editorConfig = Join-Path $root ".editorconfig"
  @"
root = true

[*.cs]
indent_style = space
indent_size = 2
charset = utf-8
insert_final_newline = true
"@ | Out-File -FilePath $editorConfig -Encoding UTF8
  Write-Host "Created: $editorConfig"

  # stylecop.json
  $stylecop = Join-Path $root "stylecop.json"
  @"
{
  ""settings"": {
    ""documentationRules"": {
      ""companyName"": ""NZFTC"",
      ""documentInterfaces"": false
    }
  }
}
"@ | Out-File -FilePath $stylecop -Encoding UTF8
  Write-Host "Created: $stylecop"

  # CONTRIBUTING.md
  $contrib = Join-Path $root "CONTRIBUTING.md"
  @"
# Contributing

Branch naming:
- feature/<initials>-short-description

Commit style:
- feat(ui): add leave form
- fix(data): correct seed script

Pull request checklist:
- Passes unit tests
- Linked issue number
- Reviewer assigned
"@ | Out-File -FilePath $contrib -Encoding UTF8
  Write-Host "Created: $contrib"

  # REQUIRED.md
  $req = Join-Path $root "REQUIRED.md"
  @"
# Required Tools and Versions

- Visual Studio 2022 Community (ASP.NET workload)
- .NET SDK 7.x (confirm with 'dotnet --list-sdks')
- dotnet-ef (dotnet tool install --global dotnet-ef)
- Git for Windows (git --version)
- DB Browser for SQLite (optional)
"@ | Out-File -FilePath $req -Encoding UTF8
  Write-Host "Created: $req"

  # .gitignore
  $gitignore = Join-Path $root ".gitignore"
  @"
# Visual Studio
.vs/
*.user
*.suo

# Build
bin/
obj/
out/

# VS Code
.vscode/

# OS
Thumbs.db
.DS_Store

# NuGet
*.nupkg
packages/

# Local DB and secrets
data/app.db
*.db
secrets.json
appsettings.*.Secrets.json

# Publish
publish/
"@ | Out-File -FilePath $gitignore -Encoding UTF8
  Write-Host "Created: $gitignore"

  # MockServices template
  $mockDir = Join-Path $root "src/$RepoName.MockServices"
  $mockReadme = Join-Path $mockDir "README.MockServices.md"
  @"
# MockServices

In-memory mock implementations for UI development. Set UseMocks = true in appsettings.Development.json to use.
"@ | Out-File -FilePath $mockReadme -Encoding UTF8

  $mockServiceFile = Join-Path $mockDir "LeaveMockService.cs"
  @"
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace $RepoName.MockServices {
  public class LeaveMockService {
    public Task<List<object>> GetLeavesAsync() {
      return Task.FromResult(new List<object> { new { Id = Guid.NewGuid(), Reason = ""Sample leave"", Start = DateTime.UtcNow } });
    }
  }
}
"@ | Out-File -FilePath $mockServiceFile -Encoding UTF8
  Write-Host "Created MockServices template at: $mockDir"

  # scripts/create-db.ps1
  $psCreateDb = Join-Path $root "scripts/create-db.ps1"
  @"
# create-db.ps1 - creates data folder and an empty app.db for local dev
\$dataPath = Join-Path (Split-Path -Parent \$PSScriptRoot) '..\data'
if (-not (Test-Path \$dataPath)) { New-Item -ItemType Directory -Path \$dataPath -Force | Out-Null }
\$dbFile = Join-Path \$dataPath 'app.db'
if (-not (Test-Path \$dbFile)) { New-Item -ItemType File -Path \$dbFile -Force | Out-Null; Write-Host 'Created empty DB file: ' \$dbFile } else { Write-Host 'DB already exists: ' \$dbFile }
"@ | Out-File -FilePath $psCreateDb -Encoding UTF8
  Write-Host "Created: $psCreateDb"

  # appsettings.Development.json
  $appSettings = Join-Path $root "src/$RepoName.Server/appsettings.Development.json"
  @"
{
  ""ConnectionStrings"": {
    ""DefaultConnection"": ""Data Source=../../data/app.db""
  },
  ""UseMocks"": true
}
"@ | Out-File -FilePath $appSettings -Encoding UTF8
  Write-Host "Created: $appSettings"
}

Write-Host "Done. Open $solutionFile in Visual Studio and create projects or run 'dotnet new' templates as required."